# Generated by Django 4.0 on 2023-12-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0002_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to="instagram/post/%Y/%m/%d"),
        ),
    ]
